/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_tienda_electronica;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author polip
 */
public class Password extends javax.swing.JFrame {

    /**
     * Creates new form Password
     * @param aux
     */
    public Password(Inventariado aux) {
        initComponents();
        inventariado = aux;
    }

    private Password() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Panel_Superior = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel_Ingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IngresarBT = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Superior.setBackground(new java.awt.Color(51, 153, 255));
        Panel_Superior.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Panel_Superior.setLayout(new java.awt.GridLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese el usuario y contraseña adecuados para entrar");
        Panel_Superior.add(jLabel4);

        getContentPane().add(Panel_Superior, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        Panel_Ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Ingreso.setLayout(new java.awt.GridLayout(6, 4, 45, 45));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setText("Usuario");
        Panel_Ingreso.add(jLabel1);

        UserTF.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        Panel_Ingreso.add(UserTF);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setText("Password");
        Panel_Ingreso.add(jLabel2);

        Password.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Panel_Ingreso.add(Password);
        Panel_Ingreso.add(jLabel5);
        Panel_Ingreso.add(jLabel6);
        Panel_Ingreso.add(jLabel7);
        Panel_Ingreso.add(jLabel8);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        Panel_Ingreso.add(jLabel3);

        IngresarBT.setBackground(new java.awt.Color(153, 255, 255));
        IngresarBT.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        IngresarBT.setForeground(new java.awt.Color(0, 153, 255));
        IngresarBT.setText("Ingresar");
        IngresarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBTActionPerformed(evt);
            }
        });
        Panel_Ingreso.add(IngresarBT);

        getContentPane().add(Panel_Ingreso, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void IngresarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBTActionPerformed
        // TODO add your handling code here:
        String pass=new String(Password.getPassword());
        if("Admin".equals(UserTF.getText()) && "123".equals(pass))
        {
            Ingreso_Productos a=new Ingreso_Productos(inventariado);
            a.setVisible(true);
            a.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            a.setSize(800,600);
            a.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Usuario Incorrecto","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IngresarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarBT;
    private javax.swing.JPanel Panel_Ingreso;
    private javax.swing.JPanel Panel_Superior;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private Inventariado inventariado;
}
