/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicinas;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author polip
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     * @param c
     * @param aux
     */
    public Consulta(Cliente c,Almacenamiento_Medicinas aux) {
        initComponents();
        File u=new File("D://fac.dat");
        Factura=new Almacenamiento_Medicinas(u);
        Factura.Borrar();
        TC =new DefaultTableModel();
        String ids [] = {"Codigo","Nombre","Fabricante","Cantidad","Precio","FE","FA","Descripcion"};
        TC.setColumnIdentifiers(ids);
        TB_Factura.setModel(TC);
        clientefinal=c;
        Medicinas=aux;
        UsuarioTx.setText("Bienvenido "+c.getNombre()+" a Supermercados Toñito");
        CategoriaCB.setModel(new DefaultComboBoxModel(Medicinas.getListadoCategorias(false)));
        
    }

    private Consulta() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Superior = new javax.swing.JPanel();
        UsuarioTx = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Principal = new javax.swing.JPanel();
        Panel_Ver = new javax.swing.JPanel();
        Panel_Informacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Factura = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CEDULA_TA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        NOMBRE_TA = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DIRECCION_TA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        PTotalJL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PagarBT = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CategoriaCB = new javax.swing.JComboBox<>();
        ProductosCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JScrollPane();
        CODIGO_TA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        PRODUCTO_TA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        PRECIO = new javax.swing.JScrollPane();
        PRECIO_TA = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        MarcaTA = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionTA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        CantidadCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        PagarB = new javax.swing.JButton();
        IMAGEN = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        FE = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        FA = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JLFondoIzq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        Panel_Superior.setBackground(new java.awt.Color(1, 82, 73));
        Panel_Superior.setAlignmentY(0.25F);
        Panel_Superior.setMaximumSize(new java.awt.Dimension(32767, 327));
        Panel_Superior.setLayout(new java.awt.GridLayout(1, 2));

        UsuarioTx.setBackground(new java.awt.Color(87, 188, 144));
        UsuarioTx.setFont(new java.awt.Font("Lucida Sans", 3, 36)); // NOI18N
        UsuarioTx.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTx.setText("Bienvenido usuario");
        Panel_Superior.add(UsuarioTx);

        jLabel2.setBackground(new java.awt.Color(87, 188, 144));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel_Superior.add(jLabel2);

        getContentPane().add(Panel_Superior);

        Panel_Principal.setLayout(new javax.swing.BoxLayout(Panel_Principal, javax.swing.BoxLayout.X_AXIS));

        Panel_Ver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Informacion.setBackground(new java.awt.Color(119, 201, 212));
        Panel_Informacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel_Informacion.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 0, -1, -1));

        TB_Factura.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        TB_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "PrecioUnitario", "PrecioTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TB_Factura);

        Panel_Informacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 680, 212));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart-add-button_icon-icons.com_56132 (1).png"))); // NOI18N
        jLabel10.setText("Carrito");
        Panel_Informacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cedula");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 30));

        CEDULA_TA.setEditable(false);
        CEDULA_TA.setBackground(new java.awt.Color(202, 235, 242));
        CEDULA_TA.setColumns(20);
        CEDULA_TA.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        CEDULA_TA.setRows(5);
        jScrollPane5.setViewportView(CEDULA_TA);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 250, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nombre");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 20));

        NOMBRE_TA.setEditable(false);
        NOMBRE_TA.setBackground(new java.awt.Color(202, 235, 242));
        NOMBRE_TA.setColumns(20);
        NOMBRE_TA.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        NOMBRE_TA.setRows(5);
        jScrollPane4.setViewportView(NOMBRE_TA);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 250, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Direccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 30));

        DIRECCION_TA.setEditable(false);
        DIRECCION_TA.setBackground(new java.awt.Color(202, 235, 242));
        DIRECCION_TA.setColumns(20);
        DIRECCION_TA.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        DIRECCION_TA.setRows(5);
        jScrollPane3.setViewportView(DIRECCION_TA);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 250, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total a pagar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 40));

        PTotalJL.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        PTotalJL.setForeground(new java.awt.Color(242, 242, 242));
        PTotalJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PTotalJL.setText("Total");
        jPanel1.add(PTotalJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 70, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(156, 210, 211));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 694, 486, 108));

        PagarBT.setBackground(new java.awt.Color(255, 59, 63));
        PagarBT.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        PagarBT.setForeground(new java.awt.Color(239, 239, 239));
        PagarBT.setText("Pagar");
        PagarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBTActionPerformed(evt);
            }
        });
        jPanel1.add(PagarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 235, 58));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondodarkblue.jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 630));

        Panel_Informacion.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 600, 460));

        Panel_Ver.add(Panel_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 0, -1, 860));

        CategoriaCB.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        CategoriaCB.setForeground(new java.awt.Color(44, 62, 80));
        CategoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Una Categoria" }));
        CategoriaCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        CategoriaCB.setOpaque(true);
        CategoriaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaCBActionPerformed(evt);
            }
        });
        Panel_Ver.add(CategoriaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 456, 80));

        ProductosCB.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        ProductosCB.setForeground(new java.awt.Color(44, 62, 80));
        ProductosCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Producto" }));
        ProductosCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        ProductosCB.setOpaque(true);
        ProductosCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosCBActionPerformed(evt);
            }
        });
        Panel_Ver.add(ProductosCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 450, 40));

        jLabel1.setBackground(new java.awt.Color(165, 165, 175));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Codigo");
        Panel_Ver.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        CODIGO.setBackground(new java.awt.Color(255, 255, 255));
        CODIGO.setForeground(new java.awt.Color(44, 62, 80));

        CODIGO_TA.setEditable(false);
        CODIGO_TA.setBackground(new java.awt.Color(255, 255, 255));
        CODIGO_TA.setColumns(20);
        CODIGO_TA.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        CODIGO_TA.setRows(5);
        CODIGO_TA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        CODIGO.setViewportView(CODIGO_TA);

        Panel_Ver.add(CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 290, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Producto");
        Panel_Ver.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, -1, -1));

        PRODUCTO_TA.setEditable(false);
        PRODUCTO_TA.setBackground(new java.awt.Color(202, 235, 242));
        PRODUCTO_TA.setColumns(20);
        PRODUCTO_TA.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        PRODUCTO_TA.setRows(5);
        PRODUCTO_TA.setText("Producto Ta?");
        jScrollPane6.setViewportView(PRODUCTO_TA);

        Panel_Ver.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 820, 272, 40));

        jLabel4.setBackground(new java.awt.Color(165, 165, 175));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio");
        Panel_Ver.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        PRECIO_TA.setEditable(false);
        PRECIO_TA.setBackground(new java.awt.Color(255, 255, 255));
        PRECIO_TA.setColumns(20);
        PRECIO_TA.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        PRECIO_TA.setForeground(new java.awt.Color(44, 62, 80));
        PRECIO_TA.setRows(5);
        PRECIO_TA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        PRECIO.setViewportView(PRECIO_TA);

        Panel_Ver.add(PRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 290, 40));

        jLabel14.setBackground(new java.awt.Color(165, 165, 175));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Marca");
        Panel_Ver.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        MarcaTA.setEditable(false);
        MarcaTA.setBackground(new java.awt.Color(255, 255, 255));
        MarcaTA.setColumns(20);
        MarcaTA.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        MarcaTA.setForeground(new java.awt.Color(44, 62, 80));
        MarcaTA.setRows(5);
        MarcaTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        jScrollPane7.setViewportView(MarcaTA);

        Panel_Ver.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 290, 40));

        jLabel7.setBackground(new java.awt.Color(165, 165, 175));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Descripcion");
        Panel_Ver.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        DescripcionTA.setEditable(false);
        DescripcionTA.setBackground(new java.awt.Color(255, 255, 255));
        DescripcionTA.setColumns(20);
        DescripcionTA.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        DescripcionTA.setForeground(new java.awt.Color(44, 62, 80));
        DescripcionTA.setRows(5);
        DescripcionTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        jScrollPane2.setViewportView(DescripcionTA);

        Panel_Ver.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 360, 119));

        jLabel6.setBackground(new java.awt.Color(165, 165, 175));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Expira");
        Panel_Ver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, -1));

        CantidadCB.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        CantidadCB.setForeground(new java.awt.Color(44, 62, 80));
        CantidadCB.setOpaque(true);
        CantidadCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadCBActionPerformed(evt);
            }
        });
        Panel_Ver.add(CantidadCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 110, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Ver.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        PagarB.setBackground(new java.awt.Color(0, 128, 128));
        PagarB.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        PagarB.setForeground(new java.awt.Color(255, 255, 255));
        PagarB.setText("Agregar al Carrito");
        PagarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBActionPerformed(evt);
            }
        });
        Panel_Ver.add(PagarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 650, 250, 102));

        IMAGEN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Ver.add(IMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 365, 343));

        FE.setEditable(false);
        FE.setBackground(new java.awt.Color(255, 255, 255));
        FE.setColumns(20);
        FE.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        FE.setForeground(new java.awt.Color(44, 62, 80));
        FE.setRows(5);
        FE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        jScrollPane8.setViewportView(FE);

        Panel_Ver.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 200, 40));

        FA.setEditable(false);
        FA.setBackground(new java.awt.Color(255, 255, 255));
        FA.setColumns(20);
        FA.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        FA.setForeground(new java.awt.Color(44, 62, 80));
        FA.setRows(5);
        FA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 235, 242)));
        jScrollPane9.setViewportView(FA);

        Panel_Ver.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 730, 200, 40));

        jLabel15.setBackground(new java.awt.Color(165, 165, 175));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cantidad");
        Panel_Ver.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        jLabel16.setBackground(new java.awt.Color(165, 165, 175));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Elaborado");
        Panel_Ver.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        JLFondoIzq.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLFondoIzq.setForeground(new java.awt.Color(255, 255, 255));
        JLFondoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo med bueno.jpg"))); // NOI18N
        Panel_Ver.add(JLFondoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        Panel_Principal.add(Panel_Ver);

        getContentPane().add(Panel_Principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaCBActionPerformed
        // TODO add your handling code here:
        //Esta linea setea el modelo de la combo box de productos
        //Tengo una funcion de categoria que devuelve un arr de objetos
        //Para acceder a esta categoria reviso en existenicas y buscao en funcion de lo que se seleccione en la combo box de categoria
       ProductosCB.setModel(new DefaultComboBoxModel(Medicinas.getListadoMedicinas(CategoriaCB.getSelectedItem().toString())));
       mostrarProducto();
    }//GEN-LAST:event_CategoriaCBActionPerformed

    private void ProductosCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosCBActionPerformed
        // TODO add your handling code here:
        mostrarProducto();
    }//GEN-LAST:event_ProductosCBActionPerformed

    private void CantidadCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadCBActionPerformed
        // TODO add your handling code here:
        //mostrarProducto();
        System.out.println("Se selecciono"+CantidadCB.getSelectedItem().toString());
        
    }//GEN-LAST:event_CantidadCBActionPerformed

    private void PagarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBActionPerformed
        // TODO add your handling code here:
        //Reviso que haya stock para dejar agregar al carrito
        if(CantidadCB.getItemCount()!=0)
        {
            //Obtengo el producto que se selecciona en base a las combo box
            //Producto aux=inventariado.getCategoria(CategoriaCB.getSelectedItem().toString()).getProducto(ProductosCB.getSelectedItem().toString());
            //Agrego el producto para modifcarlo y agregarlo y paso la cantidad seleccionada
            //aux.ReducirCantidad(Integer.parseInt(CantidadCB.getSelectedItem().toString()));
            Medicinas.RestarCantidad(ProductosCB.getSelectedItem().toString(), Integer.parseInt(CantidadCB.getSelectedItem().toString()));
            Factura.Ingresar
                (CODIGO_TA.getText(),
                CategoriaCB.getSelectedItem().toString(), 
                PRODUCTO_TA.getText(), 
                MarcaTA.getText(),
                Integer.parseInt(CantidadCB.getSelectedItem().toString()),
                 Double.parseDouble(PRECIO_TA.getText()),
                FE.getText(), 
                FA.getText(),
                DescripcionTA.getText());
            //Facturafinal.agregarProducto(aux,Integer.parseInt(CantidadCB.getSelectedItem().toString()));
            //En base a los productos que esten en la factura muestro el total que se debe pagar
            //PTotalJL.setText(String.format("%.2f",Facturafinal.getTotalProd())+"USD");
            //Llamo al metodo msotrat tabla que actualiza la tabla en base a la factura
            Factura.MostrarTabla(TC);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No hay existencias del producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        mostrarProducto();
    }//GEN-LAST:event_PagarBActionPerformed

    private void PagarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBTActionPerformed
        /*JFileChooser jFileChooser3 = new JFileChooser();
        jFileChooser3.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de datos (*.dat)", "dat");
        jFileChooser3.addChoosableFileFilter(filter);
        jFileChooser3.setDialogTitle("Selecciona una carpeta para guardar la factura");

        if (jFileChooser3.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser3.getSelectedFile();
            if (!file.getName().toLowerCase().endsWith(".dat")) {
                file = new File(file.getParentFile(), file.getName() + ".dat");
            }
            //Facturafinal.Escribir(file);
            dispose();
        }
        */
    }//GEN-LAST:event_PagarBTActionPerformed
    //Metodos mios
    public void mostrarProducto()
    {
        //Mismo que arriba, selecciono el producto en bse a los combo box
       String Nombre=ProductosCB.getSelectedItem().toString();
       //Muestro todo lo pertienente
       CODIGO_TA.setText(Medicinas.get(Nombre, "CODIGO"));
       PRODUCTO_TA.setText(Medicinas.get(Nombre, "NOMBRE"));
       PRECIO_TA.setText(Medicinas.get(Nombre, "PRECIO"));
       DescripcionTA.setText(Medicinas.get(Nombre, "DESCRIPCION"));
       //Aqui creo un combo box que va desde 1 hasta las existencias , todo se hace una funcion aparte
       CantidadCB.setModel(ModeloCantidad(Integer.parseInt(Medicinas.get(Nombre, "CANTIDAD")))); 
       MarcaTA.setText(Medicinas.get(Nombre,"FABRICANTE"));
       FE.setText(Medicinas.get(Nombre,"FE"));
       FA.setText(Medicinas.get(Nombre,"FA"));
       if(!Medicinas.get(Nombre,"FABRICANTE").equals("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"))
       {
            String path = Medicinas.get(Nombre,"DI").trim();
            File file=new File(path);
            ImageIcon aux=new ImageIcon(file.getAbsolutePath()); 
            Image xd = aux.getImage().getScaledInstance(350, 350, Image.SCALE_SMOOTH);
            aux=new ImageIcon(xd);
            IMAGEN.setIcon(aux);
       }
       
       mostrarDatos();
    }
    public void mostrarDatos()
    {
        //Muestros los datos del cliente
        CEDULA_TA.setText(clientefinal.getCedula());
        NOMBRE_TA.setText(clientefinal.getNombre());
        DIRECCION_TA.setText(clientefinal.getDireccion());
        
    }
    //Es una funcion que devuelve un modelo para una combo box desde el 1 hasta el numero de parametro
    public static DefaultComboBoxModel<String> ModeloCantidad(int i) {
        String[] elementos = new String[i];
        for (int x = 0; x < i; x++) {
            elementos[x] = String.valueOf(x + 1);
        }
        return new DefaultComboBoxModel<>(elementos);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CEDULA_TA;
    private javax.swing.JScrollPane CODIGO;
    private javax.swing.JTextArea CODIGO_TA;
    private javax.swing.JComboBox<String> CantidadCB;
    private javax.swing.JComboBox<String> CategoriaCB;
    private javax.swing.JTextArea DIRECCION_TA;
    private javax.swing.JTextArea DescripcionTA;
    private javax.swing.JTextArea FA;
    private javax.swing.JTextArea FE;
    private javax.swing.JLabel IMAGEN;
    private javax.swing.JLabel JLFondoIzq;
    private javax.swing.JTextArea MarcaTA;
    private javax.swing.JTextArea NOMBRE_TA;
    private javax.swing.JScrollPane PRECIO;
    private javax.swing.JTextArea PRECIO_TA;
    private javax.swing.JTextArea PRODUCTO_TA;
    private javax.swing.JLabel PTotalJL;
    private javax.swing.JButton PagarB;
    private javax.swing.JButton PagarBT;
    private javax.swing.JPanel Panel_Informacion;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_Superior;
    private javax.swing.JPanel Panel_Ver;
    private javax.swing.JComboBox<String> ProductosCB;
    private javax.swing.JTable TB_Factura;
    private javax.swing.JLabel UsuarioTx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
    private Almacenamiento_Medicinas Medicinas;
    private Almacenamiento_Medicinas Factura;
    private Cliente clientefinal;
    private  DefaultTableModel TC;
}
