/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medicinas;

import java.util.LinkedHashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import Medicinas.Almacenamiento_Medicinas;
import rsscalelabel.RSScaleLabel;
import java.awt.Dimension;

/**
 *
 * @author polip
 */
public class Ingreso_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_Cliente
     * @param aux
     */
    public Ingreso_Cliente(Almacenamiento_Medicinas aux) {
        initComponents();
        this.inventariado=aux;
        
    }

    private Ingreso_Cliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Cliente_Ingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CedulaTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DireccionTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ingresar_Cliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 153));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        Cliente_Ingreso.setBackground(new java.awt.Color(255, 255, 255));
        Cliente_Ingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(169, 169, 169));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido a Farmacias Doctoñito!");
        Cliente_Ingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 47));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese sus datos");
        Cliente_Ingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, 47));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 64, 64));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");
        Cliente_Ingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, 47));

        NombreTF.setBackground(new java.awt.Color(202, 235, 242));
        NombreTF.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        Cliente_Ingreso.add(NombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 300, 47));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 64, 64));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cedula");
        Cliente_Ingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, 47));

        CedulaTF.setBackground(new java.awt.Color(202, 235, 242));
        CedulaTF.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        CedulaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTFActionPerformed(evt);
            }
        });
        Cliente_Ingreso.add(CedulaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 300, 47));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Direccion");
        Cliente_Ingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, 47));

        DireccionTF.setBackground(new java.awt.Color(202, 235, 242));
        DireccionTF.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        Cliente_Ingreso.add(DireccionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 300, 47));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.darkGray);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estos datos se usaran para la facturacion");
        Cliente_Ingreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 700, -1, 47));

        Ingresar_Cliente.setBackground(new java.awt.Color(0, 102, 255));
        Ingresar_Cliente.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        Ingresar_Cliente.setForeground(new java.awt.Color(239, 239, 239));
        Ingresar_Cliente.setText("Ingresar");
        Ingresar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_ClienteActionPerformed(evt);
            }
        });
        Cliente_Ingreso.add(Ingresar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 453, 47));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket (1).png"))); // NOI18N
        Cliente_Ingreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 260, 260));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cruz-2831364_960_720-_2_.png"))); // NOI18N
        jLabel7.setText("Farmacias \"Doctoñito\"");
        Cliente_Ingreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 640, 120));

        getContentPane().add(Cliente_Ingreso, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_ClienteActionPerformed
        // TODO add your handling code here:
        if(Validar())
        {
            Consulta a=new Consulta(new Cliente(NombreTF.getText(),CedulaTF.getText(),DireccionTF.getText()),inventariado);
            a.setTitle("Menu");
            a.setVisible(true);
            a.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            a.setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Ingrese datos validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_Ingresar_ClienteActionPerformed

    private void CedulaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTFActionPerformed
    public boolean Validar()
    {
        return !NombreTF.getText().isEmpty() && !CedulaTF.getText().isEmpty() && !DireccionTF.getText().isEmpty();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CedulaTF;
    private javax.swing.JPanel Cliente_Ingreso;
    private javax.swing.JTextField DireccionTF;
    private javax.swing.JButton Ingresar_Cliente;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    private Almacenamiento_Medicinas inventariado;
}
