/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuenta_bancaria;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset; 
import org.jfree.chart.plot.PiePlot; 
import org.jfree.chart.ChartFrame;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Camilo-PC
 */
public class IngresoDatos extends javax.swing.JFrame {

    /**
     * Creates new form IngresoDatos
     */
    public IngresoDatos() {
        initComponents();
        ListaCuentas = new LinkedList<>();
    }
    public Cuenta BuscarNCuenta(String ParametroBuscar) {
    for (Cuenta cuenta : ListaCuentas) {
        if (cuenta.GetNCuenta().equals(ParametroBuscar)) {
            return cuenta;
        }
    }
    return null;
    }
    public Cuenta BuscarCICliente(String ParametroBuscar) {
    for (Cuenta cuenta : ListaCuentas) {
        if (cuenta.GetCedula().equals(ParametroBuscar)) {
            return cuenta;
        }
    }
    return null;
    }
    public void Clear(){
        TextNCuenta.setText("");
        TextCICliente.setText("");
        TextNombre.setText("");
        TextApellido.setText("");
        TextSaldo.setText("");
    }
    public void GraficarPastel()
    {
        //Para graficar hago todo lo que decia la documentacion de Jfreechart
        //Para crear el set de datos utilizo los contadores que cree
        DefaultPieDataset datos=new DefaultPieDataset();
        for (Cuenta cuenta : ListaCuentas){
            datos.setValue(cuenta.GetNombre(), cuenta.GetSaldo());
        }
        //Muestro el pastel en una ventana
        JFreeChart grafico=ChartFactory.createPieChart("Cuenta Ahorrantes y Saldo", datos,true,true,true);
        PiePlot P=(PiePlot)grafico.getPlot();
        ChartFrame frame=new ChartFrame("Grafico de pastel",grafico);
        frame.setVisible(true);
        frame.setSize(500,500);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelNCuenta = new javax.swing.JLabel();
        LabelCICliente = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        TextNCuenta = new javax.swing.JTextField();
        TextCICliente = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextApellido = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        LabelSaldo = new javax.swing.JLabel();
        TextSaldo = new javax.swing.JTextField();
        LabelBuscar = new javax.swing.JLabel();
        LabelParametro = new javax.swing.JLabel();
        TextBuscado = new javax.swing.JTextField();
        BotonBuscarCuenta = new javax.swing.JButton();
        BotonBuscarCI = new javax.swing.JButton();
        TextApellidoB = new javax.swing.JTextField();
        LabelSaldo1 = new javax.swing.JLabel();
        TextSaldoB = new javax.swing.JTextField();
        LabelNCuenta1 = new javax.swing.JLabel();
        LabelCICliente1 = new javax.swing.JLabel();
        LabelNombre1 = new javax.swing.JLabel();
        LabelApellido1 = new javax.swing.JLabel();
        TextNCuentaB = new javax.swing.JTextField();
        TextCIClienteB = new javax.swing.JTextField();
        TextNombreB = new javax.swing.JTextField();
        BotonPastel = new javax.swing.JButton();
        LabelValorDeposito = new javax.swing.JLabel();
        LabelCuentaDestino = new javax.swing.JLabel();
        BotonDepositar = new javax.swing.JButton();
        LabelValorRetirar = new javax.swing.JLabel();
        LabelRetirarCuenta = new javax.swing.JLabel();
        BotonRetirar = new javax.swing.JButton();
        TextValorDepositar = new javax.swing.JTextField();
        TextCuentaDestino = new javax.swing.JTextField();
        TextValorRetiro = new javax.swing.JTextField();
        TextCuentaRetiro = new javax.swing.JTextField();
        LabelEstadoDeposito = new javax.swing.JLabel();
        LabelEstadoRetiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setText("Cuenta Bancaria");

        LabelNCuenta.setText("# de Cuenta");

        LabelCICliente.setText("CI del Cliente");

        LabelNombre.setText("Nombre");

        LabelApellido.setText("Apellido");

        TextNCuenta.setBackground(new java.awt.Color(204, 255, 204));

        TextCICliente.setBackground(new java.awt.Color(204, 255, 204));

        TextNombre.setBackground(new java.awt.Color(204, 255, 204));

        TextApellido.setBackground(new java.awt.Color(204, 255, 204));
        TextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoActionPerformed(evt);
            }
        });

        BotonIngresar.setBackground(new java.awt.Color(51, 204, 255));
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIngresarMouseClicked(evt);
            }
        });
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });

        LabelSaldo.setText("Saldo");

        TextSaldo.setBackground(new java.awt.Color(204, 255, 204));
        TextSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSaldoActionPerformed(evt);
            }
        });

        LabelBuscar.setText("Buscar Cliente");

        LabelParametro.setText("Parámetro:");

        TextBuscado.setBackground(new java.awt.Color(204, 204, 255));

        BotonBuscarCuenta.setBackground(new java.awt.Color(255, 204, 204));
        BotonBuscarCuenta.setText("Buscar Por # Cuenta");
        BotonBuscarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarCuentaMouseClicked(evt);
            }
        });
        BotonBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarCuentaActionPerformed(evt);
            }
        });

        BotonBuscarCI.setBackground(new java.awt.Color(255, 204, 204));
        BotonBuscarCI.setText("Buscar Por CI ");
        BotonBuscarCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarCIMouseClicked(evt);
            }
        });
        BotonBuscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarCIActionPerformed(evt);
            }
        });

        TextApellidoB.setEditable(false);
        TextApellidoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoBActionPerformed(evt);
            }
        });

        LabelSaldo1.setText("Saldo");

        TextSaldoB.setEditable(false);
        TextSaldoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSaldoBActionPerformed(evt);
            }
        });

        LabelNCuenta1.setText("# de Cuenta");

        LabelCICliente1.setText("CI del Cliente");

        LabelNombre1.setText("Nombre");

        LabelApellido1.setText("Apellido");

        TextNCuentaB.setEditable(false);

        TextCIClienteB.setEditable(false);

        TextNombreB.setEditable(false);

        BotonPastel.setBackground(new java.awt.Color(255, 204, 204));
        BotonPastel.setText("Graficar Pastel");
        BotonPastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuenta_bancaria/pie_chart_icon_155907 (1).png"))); // NOI18N
        BotonPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPastelActionPerformed(evt);
            }
        });

        LabelValorDeposito.setText("Valor a Depositar:");

        LabelCuentaDestino.setText("Cuenta Destino:");

        BotonDepositar.setBackground(new java.awt.Color(204, 255, 204));
        BotonDepositar.setText("Depositar");
        BotonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDepositarActionPerformed(evt);
            }
        });

        LabelValorRetirar.setText("Valor a Retirar:");

        LabelRetirarCuenta.setText("Cuenta:");

        BotonRetirar.setBackground(new java.awt.Color(255, 204, 204));
        BotonRetirar.setText("Retirar");
        BotonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetirarActionPerformed(evt);
            }
        });

        TextValorDepositar.setBackground(new java.awt.Color(204, 204, 255));

        TextCuentaDestino.setBackground(new java.awt.Color(204, 204, 255));
        TextCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCuentaDestinoActionPerformed(evt);
            }
        });

        TextValorRetiro.setBackground(new java.awt.Color(204, 204, 255));
        TextValorRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorRetiroActionPerformed(evt);
            }
        });

        TextCuentaRetiro.setBackground(new java.awt.Color(204, 204, 255));
        TextCuentaRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCuentaRetiroActionPerformed(evt);
            }
        });

        LabelEstadoDeposito.setText("Depósito:");

        LabelEstadoRetiro.setText("Retiro: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelCICliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextCICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelNCuenta)
                                .addGap(30, 30, 30)
                                .addComponent(TextNCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BotonIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(BotonPastel)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNCuenta1)
                            .addComponent(LabelCICliente1)
                            .addComponent(LabelNombre1)
                            .addComponent(LabelApellido1)
                            .addComponent(LabelSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextApellidoB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(TextNombreB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextCIClienteB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextNCuentaB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSaldoB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEstadoRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonRetirar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelRetirarCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextCuentaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBuscar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LabelTitulo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelParametro)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(BotonBuscarCI))
                            .addComponent(BotonBuscarCuenta))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelEstadoDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonDepositar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelValorDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelCuentaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelValorRetirar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextValorDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextValorRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNCuenta)
                    .addComponent(TextNCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBuscar)
                    .addComponent(LabelValorDeposito)
                    .addComponent(TextValorDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCICliente)
                    .addComponent(TextCICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelParametro)
                    .addComponent(TextBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCuentaDestino)
                    .addComponent(TextCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarCuenta)
                    .addComponent(BotonDepositar)
                    .addComponent(LabelEstadoDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelApellido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonBuscarCI)
                        .addComponent(LabelValorRetirar)
                        .addComponent(TextValorRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSaldo)
                            .addComponent(TextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonPastel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelNCuenta1)
                                .addComponent(TextNCuentaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelRetirarCuenta)
                            .addComponent(TextCuentaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCICliente1)
                            .addComponent(TextCIClienteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRetirar)
                            .addComponent(LabelEstadoRetiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombre1)
                            .addComponent(TextNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelApellido1)
                            .addComponent(TextApellidoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSaldo1)
                            .addComponent(TextSaldoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidoActionPerformed

    private void TextSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSaldoActionPerformed

    private void BotonBuscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarCIActionPerformed
        // TODO add your handling code here:
        ParametroBuscar = TextBuscado.getText();
        Cuenta Buscado = BuscarCICliente(ParametroBuscar);
        if (Buscado != null){
            TextNCuentaB.setText(Buscado.GetNCuenta());
            TextCIClienteB.setText(Buscado.GetCedula());
            TextNombreB.setText(Buscado.GetNombre());
            TextApellidoB.setText(Buscado.GetApellido());
            TextSaldoB.setText(String.valueOf(Buscado.GetSaldo()));
        }
        else{
           TextNCuentaB.setText("Cedula No Encontrada");
           TextCIClienteB.setText("Cedula No Encontrada");
           TextNombreB.setText("Cedula No Encontrada");
           TextApellidoB.setText("Cedula No Encontrada");
           TextSaldoB.setText("Cedula No Encontrada"); 
        }
    }//GEN-LAST:event_BotonBuscarCIActionPerformed

    private void TextApellidoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidoBActionPerformed

    private void TextSaldoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSaldoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSaldoBActionPerformed

    private void BotonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIngresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngresarMouseClicked

    private void BotonBuscarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarCuentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarCuentaMouseClicked

    private void BotonBuscarCIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarCIMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarCIMouseClicked

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:
        String NCuenta = TextNCuenta.getText();
        String Nombre = TextNombre.getText();
        String Apellido = TextApellido.getText();
        String CI = TextCICliente.getText();
        double Saldo = Double.parseDouble(TextSaldo.getText());
        Cuenta Ingreso = new Cuenta(NCuenta, Nombre, Apellido, CI, Saldo);
        ListaCuentas.add(Ingreso);
        Clear();
        
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarCuentaActionPerformed
        // TODO add your handling code here:
        ParametroBuscar = TextBuscado.getText();
        Cuenta Buscado = BuscarNCuenta(ParametroBuscar);
        if (Buscado != null){
            TextNCuentaB.setText(Buscado.GetNCuenta());
            TextCIClienteB.setText(Buscado.GetCedula());
            TextNombreB.setText(Buscado.GetNombre());
            TextApellidoB.setText(Buscado.GetApellido());
            TextSaldoB.setText(String.valueOf(Buscado.GetSaldo()));
        }
        else{
           TextNCuentaB.setText("Cuenta No Encontrada");
           TextCIClienteB.setText("Cuenta No Encontrada");
           TextNombreB.setText("Cuenta No Encontrada");
           TextApellidoB.setText("Cuenta No Encontrada");
           TextSaldoB.setText("Cuenta No Encontrada"); 
        }
    }//GEN-LAST:event_BotonBuscarCuentaActionPerformed

    private void BotonPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPastelActionPerformed
        // TODO add your handling code here:
        GraficarPastel();
    }//GEN-LAST:event_BotonPastelActionPerformed

    private void BotonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDepositarActionPerformed
        // TODO add your handling code here:
        ParametroBuscar = TextCuentaDestino.getText();
        Cuenta Buscado = BuscarNCuenta(ParametroBuscar);
        if (Buscado != null){
            Buscado.Depositar(Double.parseDouble(TextValorDepositar.getText()));
            LabelEstadoDeposito.setText("Depósito: Exitoso");
            Clear();
        }
        else{
            LabelEstadoRetiro.setText("Depósito: Fallido");
        }
    }//GEN-LAST:event_BotonDepositarActionPerformed

    private void BotonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetirarActionPerformed
        // TODO add your handling code here:
        ParametroBuscar = TextCuentaRetiro.getText();
        Cuenta Buscado = BuscarNCuenta(ParametroBuscar);
        if (Buscado != null){
           if (Buscado.Retirar(Double.parseDouble(TextValorRetiro.getText())) == true){
            LabelEstadoRetiro.setText("Retiro: Exitoso");
            Clear();            
            } 
           else{
            LabelEstadoRetiro.setText("Retiro: Fallido");
            }
        }
        else{
            LabelEstadoRetiro.setText("Retiro: Fallido");
        }
    }//GEN-LAST:event_BotonRetirarActionPerformed

    private void TextCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCuentaDestinoActionPerformed

    private void TextValorRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorRetiroActionPerformed

    private void TextCuentaRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCuentaRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCuentaRetiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarCI;
    private javax.swing.JButton BotonBuscarCuenta;
    private javax.swing.JButton BotonDepositar;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton BotonPastel;
    private javax.swing.JButton BotonRetirar;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelApellido1;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelCICliente;
    private javax.swing.JLabel LabelCICliente1;
    private javax.swing.JLabel LabelCuentaDestino;
    private javax.swing.JLabel LabelEstadoDeposito;
    private javax.swing.JLabel LabelEstadoRetiro;
    private javax.swing.JLabel LabelNCuenta;
    private javax.swing.JLabel LabelNCuenta1;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel LabelParametro;
    private javax.swing.JLabel LabelRetirarCuenta;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelSaldo1;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelValorDeposito;
    private javax.swing.JLabel LabelValorRetirar;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextApellidoB;
    private javax.swing.JTextField TextBuscado;
    private javax.swing.JTextField TextCICliente;
    private javax.swing.JTextField TextCIClienteB;
    private javax.swing.JTextField TextCuentaDestino;
    private javax.swing.JTextField TextCuentaRetiro;
    private javax.swing.JTextField TextNCuenta;
    private javax.swing.JTextField TextNCuentaB;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextNombreB;
    private javax.swing.JTextField TextSaldo;
    private javax.swing.JTextField TextSaldoB;
    private javax.swing.JTextField TextValorDepositar;
    private javax.swing.JTextField TextValorRetiro;
    // End of variables declaration//GEN-END:variables
     private List<Cuenta> ListaCuentas;
     private String ParametroBuscar;
}
